/**
 * MK's own words in an old capture row's `metadata.rawTurn`.
 *
 * Old prompt capture took the newest transcript line of type `user` that had
 * text, with no meta filter, so a raw turn may be a background task's
 * notification, a skill or command body, local command output or an IDE
 * marker instead of what MK typed. The raw turn was also cut at 4,000 chars,
 * which can leave a notification without its closing tag.
 *
 * The turn is first read as a human prompt the way the transcript reader
 * reads one (CLI output and interruption markers are not prompts; a tagged
 * slash command becomes `/name args`). Complete notification and IDE blocks
 * are then removed, and a remainder that starts with machine text is
 * excluded. Anything else is kept byte for byte.
 */

import { humanPromptText } from '../capture/transcript-reader.js'

/** The length old prompt capture cut a raw turn to. */
export const RAW_TURN_CAP_CHARS = 4000

export type LegacyTextExclusion =
  /** The transcript reader does not read it as a prompt: CLI output, a bang line, an interruption, blank text. */
  | 'not_a_prompt'
  /** A notification block cut before its closing tag. */
  | 'notification_cut'
  /** A skill body. */
  | 'skill_body'
  /** A markdown heading: command and skill bodies start with one. */
  | 'heading'
  /** Command, local command, bash or system markup, a pasted block, an interruption or the caveat line. */
  | 'machine_text'
  /** Nothing is left once the blocks are removed. */
  | 'empty'

export type LegacyTextResult = { text: string } | { excluded: LegacyTextExclusion }

const REMOVED_BLOCKS: readonly RegExp[] = [
  /<task-notification>[\s\S]*?<\/task-notification>\s*/g,
  /<ide_opened_file>[\s\S]*?<\/ide_opened_file>\s*/g,
  /<ide_selection>[\s\S]*?<\/ide_selection>\s*/g,
]

const MACHINE_PREFIXES: ReadonlyArray<readonly [string, LegacyTextExclusion]> = [
  ['<task-notification>', 'notification_cut'],
  ['Base directory for this skill', 'skill_body'],
  ['# ', 'heading'],
  ['<command-', 'machine_text'],
  ['<local-command-', 'machine_text'],
  ['<system-reminder>', 'machine_text'],
  ['<bash-', 'machine_text'],
  ['<pasted_content>', 'machine_text'],
  ['[Request interrupted', 'machine_text'],
  ['Caveat: The messages below were generated by the user', 'machine_text'],
]

function removeBlocks(text: string): { text: string; removed: boolean } {
  let out = text
  for (const block of REMOVED_BLOCKS) out = out.replace(block, '')
  return out === text ? { text, removed: false } : { text: out.trim(), removed: true }
}

/** The words MK typed in a raw turn, or why it holds none. */
export function legacyUserText(rawTurn: string): LegacyTextResult {
  const prompt = humanPromptText({ type: 'user', origin: { kind: 'human' }, message: { role: 'user', content: rawTurn } })
  if (prompt === null) return { excluded: 'not_a_prompt' }
  const { text } = removeBlocks(prompt)
  if (!/\S/.test(text)) return { excluded: 'empty' }
  const lead = text.trimStart()
  for (const [prefix, reason] of MACHINE_PREFIXES) {
    if (lead.startsWith(prefix)) return { excluded: reason }
  }
  return { text }
}
