import { describe, expect, it } from 'vitest'
import { legacyUserText } from '../../src/backfill/legacy-text.js'

const NOTIFICATION =
  '<task-notification>\n<task-id>tst-task-1</task-id>\n<status>completed</status>\n<summary>Agent finished</summary>\n</task-notification>'

describe('legacyUserText', () => {
  it('excludes a notification-only turn', () => {
    expect(legacyUserText(NOTIFICATION)).toEqual({ excluded: 'empty' })
  })

  it('excludes a notification cut before its closing tag', () => {
    expect(legacyUserText(`<task-notification>\n<task-id>tst-task-2</task-id>\n<result>${'x'.repeat(200)}`)).toEqual({
      excluded: 'notification_cut',
    })
  })

  it('keeps the words that follow a notification block', () => {
    expect(legacyUserText(`${NOTIFICATION}\nok go`)).toEqual({ text: 'ok go' })
  })

  it('keeps the words that follow an IDE block', () => {
    const raw = '<ide_opened_file>The user opened the file /home/tester/tst-app/src/a.ts in the IDE.</ide_opened_file>fix the import here'
    expect(legacyUserText(raw)).toEqual({ text: 'fix the import here' })
  })

  it('excludes a command body and a skill body', () => {
    expect(legacyUserText('# Plan run\n\nRun the plan in $ARGUMENTS')).toEqual({ excluded: 'heading' })
    expect(legacyUserText('Base directory for this skill: /home/tester/.claude/skills/tst-skill\n\nDo the thing')).toEqual({
      excluded: 'skill_body',
    })
  })

  it('keeps a short prompt as typed', () => {
    expect(legacyUserText('ok')).toEqual({ text: 'ok' })
  })

  it('removes a block in the middle of a prompt and keeps the rest', () => {
    const raw = 'compare this <ide_selection>const a = 1</ide_selection> with the old version'
    expect(legacyUserText(raw)).toEqual({ text: 'compare this with the old version' })
  })

  it('keeps an untouched prompt byte for byte', () => {
    const raw = '  two leading spaces,\ttabs and a trailing newline\n'
    expect(legacyUserText(raw)).toEqual({ text: raw })
  })

  it('excludes machine text the CLI or a hook wrote', () => {
    for (const raw of [
      '<local-command-stdout>done</local-command-stdout>',
      '<local-command-caveat>Caveat: generated</local-command-caveat>',
      '<bash-input>ls</bash-input>',
      '<system-reminder>context</system-reminder>',
      '<pasted_content>pasted</pasted_content>',
      '[Request interrupted by user]',
      'Caveat: The messages below were generated by the user while running local commands.',
      '<command-message>tst is running</command-message>',
    ]) {
      expect(legacyUserText(raw)).toHaveProperty('excluded')
    }
  })

  it('excludes a blank turn', () => {
    expect(legacyUserText('   \n')).toEqual({ excluded: 'not_a_prompt' })
  })
})
